config/routes.rb
Rails.application.routes.draw do
  root 'manage_uploads#index'

  get 'manage_uploads/index' 

  get 'manage_uploads/display_records'

  post 'manage_uploads/upload_file_and_manage_users'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
require 'roo'

class NotSupportedFile < StandardError; end;
class ToLargeFile < StandardError; end;

class User < ApplicationRecord
  SUPPORTED_FORMATES = %w(.csv .xls .xlsx)
  COLUMNS = %w(id first_name last_name email password)

  validates :first_name, :last_name, :email, :password, presence: true
  validates_uniqueness_of :email
  validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}

  def self.create_from_file(files)
    files.each do |file|
      excel_file = open_spreadsheet(file)
      headers = excel_file.row(1).collect(&:downcase)
      (2..excel_file.last_row).each do |row|
        create(prepare_data(headers, excel_file, row))
      end
      FileUtils.remove_file(file, force: true)
    end
  end

  def self.prepare_data(headers, excel_file, row)
    data_from_file = headers.zip(excel_file.row(row)).to_h
    data_from_file.select{|header, value| p COLUMNS.include?(header)}
  end

  def self.open_spreadsheet(file)
    Roo::Spreadsheet.open(file, extension: :xlsx)
  end

  def self.reject_if_unknown_file(files)
    raise NotSupportedFile.new('Some Of The Files Not Supported.') if unknow_formates_present?(files)
  end

  def self.unknow_formates_present?(files)
    files.select{|file| SUPPORTED_FORMATES.exclude?(File.extname(file.original_filename))}.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/manage_uploads_controller.rb
class ManageUploadsController < ApplicationController
  before_action :set_users, only: :display_records

  def index
  end

  def upload_file_and_manage_users
    User.reject_if_unknown_file(files_from_params)
    User.delay.create_from_file(collect_temp_files)
    flash[:success] = 'Files Added for the proccessing successfully.'
    redirect_to root_path
  rescue => exception
    flash[:notice] = exception.message
    redirect_to root_path
  end

  def display_records
  end

  private

  def set_users
    @users = User.all
  end

  def files_from_params
    params.require(:excel_files)
  end

  def collect_temp_files
    files_from_params.collect do |file|
      tmp = file.tempfile
      raise ToLargeFile.new("#{file.original_filename} is too large to handle.") if file.size > 10240000
      destiny_file = File.join('public', 'uploads', file.original_filename)
      FileUtils.move "//#{tmp.path}", destiny_file
      destiny_file
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manage_uploads_helper.rb
module ManageUploadsHelper
end

app/views/layouts/_flash.html.erb
<% if flash.present? %>
  <ul>
    <% flash.each do |type, message| %>
      <li>
        <%= message%>
      </li>
    <% end %>
    <% flash.clear %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExcelUploadDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/manage_uploads/display_records.html.erb
<h3>Users From Database</h3>
<table border=1>
  <thead>
    <tr>
      <th>ID</th>
      <th>FISRT NAME</th>
      <th>LAST NAME</th>
      <th>EMAIL</th>
      <th>PASSWORD</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user|%>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</br>
</br>
<%= link_to 'upload file', root_path %>

app/views/manage_uploads/index.html.erb
<h3>upload Excel files</h3>
<%= link_to 'Sample File', 'sample_excel.xlsx', title: 'sample file for format.' %><br>
<%= form_tag( manage_uploads_upload_file_and_manage_users_path , method: :post, multipart: true) do %>
  <%= label_tag :excel_files, "Upload File" %>
  <%= file_field_tag 'excel_files[]', accept: ".xlsx, .xls, .csv", multiple: true %></br>
  <%= submit_tag("Upload") %>
<% end %>
<br>
<%= link_to 'Saved Data', manage_uploads_display_records_path %>